### ISSUE TITLE
Exception Loop on latest release

### ISSUE THREAD

**Issue by mattvirus** [nat-neels/homeassistant_russound#2]
Logger: custom_components.russound_rio3.rio
Source: custom_components/russound_rio3/rio.py:240
Integration: russound_rio3
First occurred: 1:36:36 AM (1 occurrences)
Last logged: 1:36:36 AM
Unhandled exception in IO loop

Traceback (most recent call last):
  File "/config/custom_components/russound_rio3/rio.py", line 240, in _ioloop
    response = net_future.result()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 632, in readuntil
    await self._wait_for_data('readuntil')
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by nat-neels** [comment]
You're still using Python 3.9. This has been updated to work with python 3.10 and higher, please update your HA to the latest version.

**Comment by mattvirus** [comment]
sorry! forgot i had to roll back due to a venstar firmware issue with thermostat.  doh!

**Comment by nat-neels** [comment]
I have added the old file as well and updated the instructions for python 3.10 vs 3.9.
