### ISSUE TITLE
Installing russound_rio3 doesn´t work

### ISSUE THREAD

**Issue by heidle78** [nat-neels/homeassistant_russound#3]
Hello, since a while I haven´t used my HA:
Home Assistant 2023.3.5
Supervisor 2023.03.2
Operating System 9.5
Frontend 20230309.1 - latest

I tried to install now my MCA C5 via your instruction and it doesn´t show up anywhere. No integration card, nothing is showing up and I don´t know where to start and what to check. Python is 3.10

**Comment by heidle78** [comment]
With the debug log I see something happening, but no cards or entities

2023-03-23 10:12:03.194 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[6].status = OFF
2023-03-23 10:12:03.194 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[6].status = OFF
2023-03-23 10:12:03.194 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[6].status = OFF
2023-03-23 10:12:03.195 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[6].name = Wohnen
2023-03-23 10:12:03.195 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[7].status = OFF
2023-03-23 10:12:03.195 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[7].status = OFF
2023-03-23 10:12:03.195 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[7].status = OFF
2023-03-23 10:12:03.195 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[7].name = Zone 7
2023-03-23 10:12:03.195 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[8].status = OFF
2023-03-23 10:12:03.195 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[8].status = OFF
2023-03-23 10:12:03.196 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[8].status = OFF
2023-03-23 10:12:03.196 DEBUG (MainThread) [custom_components.russound_rio_3.rio] Zone Cache retrieve C[1].Z[8].name = Zone 8

**Comment by mkaatman** [comment]
Same amp here.

Home Assistant 2023.4.5
Supervisor 2023.04.0
Frontend 20230411.1 - latest
Python 3.10.10

```
Error while setting up russound_rio platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/russound_rio_3/media_player.py", line 68, in async_setup_platform
    await russ.watch_zone(zone_id)
  File "/config/custom_components/russound_rio_3/rio.py", line 388, in watch_zone
    r = yield from self._send_cmd(
  File "/config/custom_components/russound_rio_3/rio.py", line 284, in _send_cmd
    r = yield from future
  File "/config/custom_components/russound_rio_3/rio.py", line 262, in _ioloop
    ty, value = self._process_response(response)
  File "/config/custom_components/russound_rio_3/rio.py", line 202, in _process_response
    raise CommandException(payload)
custom_components.russound_rio_3.rio.CommandException: InvalidKey (error near: WATCH C[7].Z[1] ON^)
```

In hindsight, this seems like a different issue than the original one but the same amp. I can split it off into a separate issue if need be.

@heidle78 did you ever get yours to work? I'm also curious, does it have a web interface if you hit the IP in the browser?

In HA log I see `2023-04-22 12:25:04.462 INFO (MainThread) [custom_components.russound_rio_3.rio] Connected`

In [media_player.py](https://github.com/nat-neels/homeassistant_russound/blob/main/media_player.py#L59) I tried adding some logging.

```python
    await russ.connect()

    # Discover sources, presets and zones
    sources = await russ.enumerate_sources()
    _LOGGER.warning("Sources:", sources)
    presets = await russ.enumerate_presets()
    _LOGGER.warning("Presets:", presets)
    valid_zones = await russ.enumerate_zones()
    _LOGGER.warning("Zones:", valid_zones)
```

I suspect my logger is malformed in some way but I do see these logs:
`Bad logger message: Sources: (([(1, 'FM', 'RNET AM/FM Tuner (Internal)'), (2, 'Chromecast', 'Misc Audio'), (3, 'RS-Sonos', 'Misc Audio'), (4, 'RS-Denon', 'Misc Audio'), (5, 'RS-Bluetooth', 'Misc Audio')],))`

`Bad logger message: Presets: (([],))`

```
Bad logger message: Zones: (([(<custom_components.russound_rio_3.rio.ZoneID object at 0x7f677afc9ae0>, 'Zone 1'), (<custom_components.russound_rio_3.rio.ZoneID object at 0x7f677af3aef0>, 'Zone 2'), (<custom_components.russound_rio_3.rio.ZoneID object at 0x7f6789c235e0>, 'Zone 3'), (<custom_components.russound_rio_3.rio.ZoneID object at 0x7f677ffa1930>, 'Master Bat'), (<custom_components.russound_rio_3.rio.ZoneID object at 0x7f67895bad10>, 'Zone 5'), (<custom_components.russound_rio_3.rio.ZoneID object at 0x7f677d5598a0>, 'Deck'), (<custom_components.russound_rio_3.rio.ZoneID object at 0x7f677d1119f0>, 'Main Level'), (<custom_components.russound_rio_3.rio.ZoneID object at 0x7f677fd366b0>, 'Media')],))
```

Then I tried to go into [rio.py](https://github.com/nat-neels/homeassistant_russound/blob/main/rio.py#L409) and add some logging on enumerate_sources but I never see these logs.

```python
    @asyncio.coroutine
    def enumerate_sources(self):
        """ Return a list of (source_id, source_name, source_type) tuples """
        sources = []
        logger.info("Starting source enumeration", self)
        for source_id in range(1, 17):
            try:
                source_name = yield from self.get_source_variable(source_id, 'name')
                source_type = yield from self.get_source_variable(source_id, 'type')
                logger.info("enumeration name type", source_name, source_type)
                if source_name and source_type:
                    sources.append((source_id, source_name, source_type))
            except CommandException:
                break
        return sources
```

I'm sure my code changes are being run because I had a couple of typos along the way which it failed on.

Really confused where it's failing. The error is on the index of watch_zone. `C[7].Z[1]` 

The error goes away if I modify this line in media_player.py:

From:
`        for controller in range(1, 8):`

To:
`        for controller in range(1, 6):`

However, despite no errors nothing shows up in media.

I just fried the amp trying to update the firmware. Support no longer needed. :(

**Comment by mkaatman** [comment]
I have an mca-88 now. Same problem. No errors in log but nothing shows up in media.

@mattvirus pointed out that they show up as media_player entities.

Hit "e" while in homeassistant and type: "media_player." and you should see your zones.

**Comment by mattvirus** [comment]
the zones won't show up in "media".  It's not a source that you can direct audio to via home assistant, you can only specify the input and turn it on/off.
